export const CHATS_REPOSITORY = Symbol('CHATS_REPOSITORY')
export const CHATS_SERVICE = Symbol('CHATS_SERVICE')

export const CHATS_MEMBERS_REPOSITORY = Symbol('CHATS_MEMBERS_REPOSITORY')
export const CHATS_MEMBERS_SERVICE = Symbol('CHATS_MEMBERS_SERVICE')

export const CHATS_MESSAGES_REPOSITORY = Symbol('CHATS_MESSAGES_REPOSITORY')
export const CHATS_MESSAGES_SERVICE = Symbol('CHATS_MESSAGES_SERVICE')

export const CHATS_MESSAGES_READ_REPOSITORY = Symbol('CHATS_MESSAGES_READ_REPOSITORY')

export const AUDIO_REPOSITORY = Symbol('AUDIO_REPOSITORY')

export const LINK_REPOSITORY = Symbol('LINK_REPOSITORY')

export const CHATS_MESSAGES_DELETED = Symbol('CHATS_MESSAGES_DELETED')
